module.exports = {
	getConfigFields() {
		return [
			{
				type: 'static-text',
				id: 'info',
				width: 12,
				label: 'Information',
				value: 'This module pings a remote host and updates Feedbacks and Variables accordingly.',
			},
			{
				type: 'textinput',
				id: 'ip',
				width: 6,
				label: 'Host IP Address',
				default: '192.168.0.1',
			},
			{
				type: 'textinput',
				id: 'mac',
				width: 6,
				label: 'Host MAC Address (if known)',
				default: '00:00:00:00:00:00',
			},
			{
				type: 'checkbox',
				id: 'arpLookup',
				label: 'Attempt ARP Lookup of MAC Address',
				default: true,
				width: 3,
			},
			{
				type: 'static-text',
				id: 'hr1',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'static-text',
				id: 'pinginfo',
				width: 12,
				label: 'Ping Settings',
			},
			{
				type: 'number',
				id: 'timeout',
				width: 3,
				label: 'Timeout (in seconds)',
				default: 10,
			},
			{
				type: 'static-text',
				id: 'timeoutinfo',
				width: 9,
				label: '',
				value: 'Timeout in seconds the ping should wait for a response until it is considered a failure/offline.',
			},
			{
				type: 'number',
				id: 'retryrate',
				width: 3,
				label: 'Retry Rate (in ms)',
				default: 60000,
			},
			{
				type: 'static-text',
				id: 'retryrateinfo',
				width: 9,
				label: '',
				value: 'How long to wait after the ping has finished before sending another ping.',
			},
			{
				type: 'static-text',
				id: 'hr2',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'static-text',
				id: 'wolinfo',
				width: 12,
				label: 'WOL Settings',
			},
			{
				type: 'textinput',
				id: 'wolPort',
				width: 3,
				label: 'UDP Port',
				default: 9,
			},
			{
				type: 'static-text',
				id: 'wolPortInfo',
				width: 9,
				label: '',
				value: 'UDP Port to send the WOL packet to. Default is Port 9.',
			},
			{
				type: 'textinput',
				id: 'wolBroadcast',
				width: 3,
				label: 'Broadcast Address',
				default: '255.255.255.255',
			},
			{
				type: 'static-text',
				id: 'wolBroadcastinfo',
				width: 9,
				label: '',
				value: 'Broadcast Address to send the WOL packet to. Default is 255.255.255.255.',
			},
			{
				type: 'textinput',
				id: 'wolResend',
				width: 3,
				label: 'Resend Attempts',
				default: 3,
			},
			{
				type: 'static-text',
				id: 'wolResendInfo',
				width: 9,
				label: '',
				value: 'How many times to resend the WOL packet.',
			},
			{
				type: 'textinput',
				id: 'wolInterval',
				width: 3,
				label: 'Interval between Packet Resends (in ms)',
				default: 100,
			},
			{
				type: 'static-text',
				id: 'wolIntervalInfo',
				width: 9,
				label: '',
				value: 'How long to wait between resending the WOL packet.',
			},
			{
				type: 'static-text',
				id: 'hr3',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'checkbox',
				id: 'verbose',
				label: 'Enable Verbose Logging',
				default: false,
			},
		]
	},
}
